In [1]:
import torch
import numpy as np

In [2]:
# numpy to torch tensor
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
torch2np = torch_data.numpy()
print(
    'numpy\n', np_data,
    '\ntorch\n', torch_data,
    '\ntorch2np\n', torch2np
)

numpy
 [[0 1 2]
 [3 4 5]] 
torch
 tensor([[ 0,  1,  2],
        [ 3,  4,  5]]) 
torch2np
 [[0 1 2]
 [3 4 5]]


In [3]:
# list to torch tensor
list_data = [1, -2, 3, -4]
torch_data = torch.FloatTensor(list_data)  # float-32
print(
    'list\n', list_data,
    '\ntorch\n', torch_data,
)

list
 [1, -2, 3, -4] 
torch
 tensor([ 1., -2.,  3., -4.])


In [4]:
# Matrix multiplication
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)  # float-32
print(
    'mm\n', torch.mm(tensor, tensor),
    '\navg\n', torch.mean(tensor)
)

mm
 tensor([[  7.,  10.],
        [ 15.,  22.]]) 
avg
 tensor(2.5000)
